settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
- name: /home/kms/work/go/src/github.com/Akenaide/wsoffcli
  path: /home/kms/work/go/src/github.com/Akenaide/wsoffcli
  commands:
    vet:
      status: true
    fmt:
      status: true
    test:
      status: true
      args:
        - "./..."
    install:
      status: true
    run:
      status: false
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
