name: Go

on:
  push:
    branches: [ master ]
    tags: "*"
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: "./build.sh"

    - name: Test
      run: go test -v ./...
      
    - name: Automatic Releases
      # You may pin to the exact commit or the version.
      # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Git tag (for automatic releases)
        # Should this release be marked as a draft?
        draft: false
        # Should this release be marked as a pre-release?
        prerelease: false
        # Release title (for automatic releases)
        # Assets to upload to the release
        files: build/*
